Enhancement/data types validation
cloud4rpi/cloud4rpi pull request #20
Opened 2017-12-05 14:20 UTC by sky3d

Variables types validation with errors/warnings in unsupported cases

2017-12-05 16:02 UTC, Himura2la requested changes

2017-12-05 16:02 UTC, Himura2la commented on cloud4rpi/errors.py
> +                'is expected. It will cause an error soon. ' \
soon?
How soon?

```
'WARNING! A string "%s" passed to a numeric variable. ' \
'Change the variable type or the passed value.'
```

2017-12-07 11:49 UTC, vutenkov approved these changes

2017-12-07 12:01 UTC, Himura2la approved these changes

2017-12-20 08:32 UTC, const314 approved these changes

2017-12-20 08:33 UTC, merged