Omega2 support
cloud4rpi/cloud4rpi pull request #8
Opened 2017-02-25 11:33 UTC by Himura2la

2017-05-04 14:46 UTC, sky3d requested changes

2017-05-04 14:46 UTC, sky3d commented on examples/omega2/README.md
>  -----------------------------
Please add here the list of the example links

2017-05-04 14:46 UTC, sky3d commented on examples/omega2/expansion_board.py
> +        'Operating System': " ".join(uname()),
Would be better to use 'OS Name' for better compatibility with raspberrypi examples
and extend with the 'IPAddress' value.  I hope just 'Version' will be clear in the omega context.

2017-05-04 14:46 UTC, sky3d commented on examples/omega2/omega2.py
> +    def get_omega_version():
rename to 'get_version()'

2017-05-04 14:46 UTC, sky3d commented on examples/omega2/led.py
> +    diagnostics = {
See above

2017-05-04 14:46 UTC, sky3d commented on examples/omega2/expansion_board.py
> +# -*- coding: utf-8 -*-
Consider to rename this sample to 'led_blinking' or 'led_control' ?

2017-05-04 14:46 UTC, sky3d commented on examples/omega2/expansion_board.py
> +        'RGB LED - Red': {
'Red|Blue|Green LED' should be simpler. Right?

2017-05-04 14:46 UTC, sky3d commented on examples/omega2/omega2.py
> +    def led_control(self, state, delay_on=None, delay_off=None,
Is it a part of device? The 'omege2' module should include only device specific methods. Consider to extract LED-operations code (such as `self.led_path = "/sys/class/leds/%s:amber:system/" % self.version`) to the separated file (like the ds18b20 sensors)

2017-06-02 09:40 UTC, sky3d commented
Needs to port examples to latest cloud4rpi lib

2017-06-14 08:11 UTC, sky3d commented
All raspberrypi examples moved to the specific [repository](https://github.com/cloud4rpi/cloud4rpi-examples). Pull request should be moved there

2017-06-14 14:42 UTC, Himura2la commented
I'm going to implement the requested changes here and move the resulting code into the new repo

2017-06-14 14:45 UTC, Himura2la commented on examples/omega2/omega2.py
> +    def led_control(self, state, delay_on=None, delay_off=None,
This is an Omega2 onboard LED https://docs.onion.io/omega2-docs/the-omega-led.html I thing it is strongly device-stecific

2017-06-14 14:46 UTC, Himura2la commented on examples/omega2/expansion_board.py
> +# -*- coding: utf-8 -*-
This will not work on a pure $5 Omega2. The GRB LED is located on the expansion board

2017-06-14 14:51 UTC, sky3d commented on examples/omega2/omega2.py
> +    def led_control(self, state, delay_on=None, delay_off=None,
Thanks for link. Yes, it's ok

2017-06-14 14:54 UTC, Himura2la commented on examples/omega2/expansion_board.py
> +        'RGB LED - Red': {
This is a single RGB LED, not three LEDs in row. I my names are better

2017-06-14 14:55 UTC, Himura2la commented on examples/omega2/led.py
> +    diagnostics = {
what exactly?

2017-06-14 14:59 UTC, sky3d commented on examples/omega2/led.py
> +    diagnostics = {
the same thing as in the other example at https://github.com/cloud4rpi/cloud4rpi/pull/8#discussion_r103456749

2017-06-14 15:03 UTC, Himura2la commented on examples/omega2/led.py
> +    diagnostics = {
OK, If it's about **OS Name** and **IPAddress**, I'll make it consistent with raspberrypi examples. In the new PR, I'm going to change the raspberrypi examples

2017-07-25 18:35 UTC, Himura2la commented
Merged into https://github.com/cloud4rpi/cloud4rpi-examples

2017-07-25 18:35 UTC, closed without merging