C.H.I.P support
cloud4rpi/cloud4rpi pull request #9
Opened 2017-02-25 11:34 UTC by Himura2la

2017-05-04 14:44 UTC, sky3d requested changes

2017-05-04 14:44 UTC, sky3d commented on examples/chip/gpio.py
> +        'Operating System': " ".join(uname()),
Would be better to use 'IPAddress' and 'OS Name' for better compatibility with raspberrypi examples

2017-05-04 14:44 UTC, sky3d commented on examples/chip/minimal.py
> +import chip
The concept of 'minimal example' implies the most simple code of using dummy data instead of real deal with a device. Please review the raspberrypi/minimal.py

2017-05-04 14:44 UTC, sky3d commented on examples/chip/README.md
> +-------------------------------------------------------------------------------
The list of the example-links should be here

2017-05-04 14:47 UTC, Himura2la commented on examples/chip/gpio.py
> +        'Operating System': " ".join(uname()),
Or maybe it's better to change the raspberrypi examples? This code fixes things I don't like in raspberrypi examples and propose this to be changed there also.

2017-05-04 14:49 UTC, Himura2la commented on examples/chip/minimal.py
> +import chip
maybe we should rename this one, because the file you refer to (raspberrypi/minimal.py) is platform-independent.

2017-05-04 14:50 UTC, Himura2la commented on examples/chip/minimal.py
> +import chip
maybe we should rename this one, because the file you refer to (raspberrypi/minimal.py) is platform-independent.

2017-05-04 14:51 UTC, Himura2la commented on examples/chip/README.md
> +-------------------------------------------------------------------------------
I'll add them, thanks

2017-06-02 09:40 UTC, sky3d commented
Needs to port examples to latest cloud4rpi lib

2017-06-14 08:11 UTC, sky3d commented
All raspberrypi examples moved to the specific [repository](https://github.com/cloud4rpi/cloud4rpi-examples). Pull request should be moved there

2017-06-14 14:41 UTC, Himura2la commented
I'm going to implement the requested changes here and move the resulting code into the new repo

2017-07-25 18:34 UTC, Himura2la commented
Merged into https://github.com/cloud4rpi/cloud4rpi-examples

2017-07-25 18:34 UTC, closed without merging